sudo: required
services:
  - docker

before_install:
  - docker build -t vit/docker-fe1 -f Dockerfile.dev .

script:
  - docker run vit/docker-fe1 npm run test -- --coverage

deploy:
  provider: elastickbeanstalk
  region: us-west-02
  app: "docker-fe1"
  env: "docker-env"
  bucket_name: "s3 bucket name"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"